name: Run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */10 * * *"

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      # Проверка кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Получение полной истории коммитов

      # Настройка окружения Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 # Укажите требуемую версию Python

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Запуск скрипта main.py
      - name: Run main.py
        run: python main.py

      # Очистка каталогов __pycache__
      - name: Clean up __pycache__
        run: |
          find . -name "__pycache__" -type d -exec rm -rf {} +

      # Коммит и отправка изменений в репозиторий
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master # Синхронизация с удалённой веткой master
          git add .
          git commit -m "♻️ $(TZ='Asia/Ashgabat' date '+%Y-%m-%d %H:%M:%S') Collected"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
